import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./_components/Navbar";

export const metadata: Metadata = {
  title: "E-NEST",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* Container for centering layout */}
        <Navbar />
        <div className="container mx-auto my-4 px-4 lg:px-8">
          {children}
        </div>
      </body>
    </html>
  );
}
